var buttonColors = ["green", "red", "yellow", "blue"];
var gamePattern = [];    //stores the random pattern in which the background should change colour 
var userPattern = [];    //stores the keys pressed by the user
var firstTime = false;
var level = 0;




//event when start is pressed
$("h3").click(function () {
    if (!firstTime) {
        $("h3").text(" ");
        $("h1").text("LEVEL" + level);
        nextSequence();
        firstTime = false;
    }

    // for (var i = 0; i < gamePattern.length; i++) {
    //     var color = gamePattern[i];
    //     $("body").css("background-color", color).delay(1000).queue(function (next) {
    //         $(this).css("background-color", "#011f3f");
    //         next();
    //     });
    // }

});

//event when one of the 4 coloured buttons are pressed
$(".button").click(function () {
    var buttonID = $(this).attr("id");
    userPattern.push(buttonID);
    playSound(buttonID);
    animate(buttonID);

    checkAnswer(userPattern.length - 1);
    // switch (buttonID) {
    //     case "green":
    //         $(this).addClass("pressed").delay(100).queue(function (next) {
    //             $(this).removeClass("pressed");
    //             next();
    //             var greenSound = new Audio("sounds/green.mp3");
    //             greenSound.play();
    //             console.log("green");
    //         });
    //         userPattern.push(buttonID);
    //         break;
    //     case "red":
    //         $(this).addClass("pressed").delay(100).queue(function (next) {
    //             $(this).removeClass("pressed");
    //             next();
    //             var redSound = new Audio("sounds/red.mp3");
    //             redSound.play();
    //             console.log("red");
    //         });
    //         userPattern.push(buttonID);
    //         break;
    //     case "yellow":
    //         $(this).addClass("pressed").delay(100).queue(function (next) {
    //             $(this).removeClass("pressed");
    //             next();
    //             var yellowSound = new Audio("sounds/yellow.mp3");
    //             yellowSound.play();
    //             console.log("yellow");
    //         });
    //         userPattern.push(buttonID);
    //         break;
    //     case "blue":
    //         $(this).addClass("pressed").delay(100).queue(function (next) {
    //             $(this).removeClass("pressed");
    //             next();
    //             var blueSound = new Audio("sounds/blue.mp3");
    //             blueSound.play();
    //             console.log("blue");
    //         });
    //         userPattern.push(buttonID);
    //         break;
    //     default: console.log("no button exists");
    // }
});

//random sequence of color to display on the background
function nextSequence() {
    userPattern = [];
    level++;
    $("h1").text("LEVEL " + level);
    randomNummber = Math.floor(Math.random() * 4);
    var randomColorGenerated = buttonColors[randomNummber];
    gamePattern.push(randomColorGenerated);
    $("body").css("background-color", randomColorGenerated).delay(1000).queue(function (next) {
        $(this).css("background-color", "#011f3f");
        next();
    });
    playSound(randomColorGenerated);
}


//playing all sounds
function playSound(nameOfSound) {
    var audio = new Audio("sounds/" + nameOfSound + ".mp3");
    audio.play();
}
//all animations
function animate(nameOfClass) {
    $("#" + nameOfClass).addClass("pressed").delay(100).queue(function (next) {
        $(this).removeClass("pressed");
        next();
    });
}
//checks the result of user with the one generated by nextsequence function
function checkAnswer(currentLevel) {

    if (gamePattern[currentLevel] === userPattern[currentLevel]) {
        console.log("success");

        if (userPattern.length === gamePattern.length) {
            setTimeout(function () {
                nextSequence();
            }, 1000);
        }

    }
    else {
        console.log("wrong");
        playSound("wrong");
        $("body").addClass("game-over");
        setTimeout(function () {
            $("body").removeClass("game-over");
        }, 200);
        $("h1").text("Game Over");
        $("h3").text("RESTART");
    }
}